# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  dev:
    desc: spin up container
    cmd: "dagger call build-image up --ports 3000:3000 --no-init"
