# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  default:
    cmds:
      - task -l
      - dagger functions
  dev:
    desc: spin up container
    cmd: "dagger call grt up --no-init --insecure-root-capabilities --ports 3000:3000"
